# -*- coding: utf-8 -*-
"""1_AI_Project_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NjIDpm4mSYNrhcsnnK6gwabnmnGAKSz
"""

# Commented out IPython magic to ensure Python compatibility.
from sklearn import metrics
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns                    #Seaborn is used for the scatterplot
sns.set(style="white", color_codes=True)

path = "/content/drive/MyDrive/AI Bootcamp (2024)/Dataset/Iris.csv"
df = pd.read_csv(path)
df.head()

sns.FacetGrid(df, hue="Species", height=6).map(plt.scatter, "PetalLengthCm", "PetalWidthCm").add_legend()

flower_mapping = {
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
}

df["Species"] = df["Species"].map(flower_mapping)

x=df[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]].values
y=df[["Species"]].values

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x,y)
model.score(x,y)

expected = y
predicted = model.predict(x)
predicted

print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))